/*
*
*	-= PSF DEFINIÇÃO DO USUÁRIO =-
*	Protioso String Funções
*	Autor: Protioso ([VGS]Protioso_OC)
*   Obs.: Os valores deste arquivo podem ser editados!
*
*/

#define MAX_PCOD_CHAR 256 		/*
								 	 Isto define o tamanho máximo que poderá ser
									codificado.
------------------------------------------------------------------------------*/
#define MAX_SUBSTITUIR_CHAR 256 /*
								 	 Isto define o tamanho máximo da string que
									que terá o(s) caractere(s) substituído(s).
------------------------------------------------------------------------------*/
#define MAX_psf_strtokCI 128 	/*
								 	 Isto define o tamanho máximo, da string,
									que será retornado na função psf_strtokCI.
------------------------------------------------------------------------------*/

#define MAX_psf_strtokCL 128 	/*
								 	 Isto define o tamanho máximo, da string,
									que	será retornado na função psf_strtokCL.
------------------------------------------------------------------------------*/
							
#define MAX_psf_strtok 128 		/*
								 	 Isto define o tamanho máximo, da string,
									que	será retornado na função MAX_psf_strtok.
------------------------------------------------------------------------------*/

#define MAX_psf_char_separador 3 /*
								 	 Isto define o tamanho máximo, do separador.
------------------------------------------------------------------------------*/
