/*
*
*	-= P-STREAMER =-
*	Protioso Streamer
*	Autor: Protioso ([VGS]Protioso_OC)
*   Obs.: os valores abaixo podem ser editados conforme sua necessidade!
*
*/

#if !defined MAX_PCS
	#define MAX_PCS 350
/* Limite de checkpoints (altere como preferir). */
#endif

#if !defined PCS_TEMPO_CHECAGEM
	#define PCS_TEMPO_CHECAGEM 500
/* Tempo em milisegundos. */
#endif

#if !defined PCS_RAIO_STREAM_PADRAO
	#define PCS_RAIO_STREAM_PADRAO 30.0
/* Não usado no include, apenas para você
ter uma base e/ou usar em seus scripts */
#endif

